# Generated by Django 5.2.11 on 2026-02-25 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('consumer', 'Consumer'), ('developer', 'Developer'), ('admin', 'Admin')], default='consumer', max_length=15),
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('framework', models.CharField(max_length=50)),
                ('version', models.CharField(default='1.0.0', max_length=10)),
                ('model_file', models.FileField(upload_to='models/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
