# Generated by Django 5.2.11 on 2026-03-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_role_aimodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='input_type',
            field=models.CharField(blank=True, choices=[('text', 'Text Input'), ('file', 'File Upload')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='is_interactive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='output_type',
            field=models.CharField(blank=True, choices=[('text', 'Text Result'), ('file', 'File/Image Download')], max_length=50, null=True),
        ),
    ]
