# Generated by Django 5.2.12 on 2026-03-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aimodel_input_type_aimodel_is_interactive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='output_extension',
            field=models.CharField(blank=True, choices=[('.docx', 'Word Document (.docx)'), ('.csv', 'CSV Spreadsheet (.csv)'), ('.txt', 'Text File (.txt)')], default='.docx', max_length=10, null=True),
        ),
    ]
