# Generated by Django 5.2.13 on 2026-04-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_modelusage_output_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelusage',
            name='output_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
