# Generated by Django 5.2.13 on 2026-04-16 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_modelusage_output_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelusage',
            name='output_file',
        ),
    ]
