# Generated by Django 5.2.12 on 2026-03-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_aimodel_output_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='output_extension',
            field=models.CharField(blank=True, choices=[('.docx', 'Word Document (.docx)'), ('.csv', 'CSV Spreadsheet (.csv)'), ('.txt', 'Text File (.txt)'), ('.pdf', 'PDF Document (.pdf)'), ('.png', 'Image File (.png)')], default='.docx', max_length=10, null=True),
        ),
    ]
