# Generated by Django 5.2.13 on 2026-04-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_modelusage_output_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='ui_config_file',
            field=models.FileField(blank=True, null=True, upload_to='ui_configs/'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='input_type',
            field=models.CharField(blank=True, choices=[('text', 'Text Input'), ('file', 'File Upload'), ('custom', 'Custom UI (JSON Config)')], max_length=50, null=True),
        ),
    ]
