# Generated by Django 5.2.13 on 2026-04-23 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_aimodel_ui_config_file_alter_aimodel_input_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/'),
        ),
    ]
