# Generated by Django 5.2.12 on 2026-04-06 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_aimodel_output_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='output_extension',
            field=models.CharField(blank=True, choices=[('', 'Custom/Detect from Code'), ('.docx', 'Word Document (.docx)'), ('.csv', 'CSV Spreadsheet (.csv)'), ('.txt', 'Text File (.txt)'), ('.pdf', 'PDF Document (.pdf)'), ('.png', 'Image File (.png)'), ('.xlsx', 'Excel Spreadsheet (.xlsx)'), ('.zip', 'Zip Archive (.zip)'), ('.json', 'JSON File (.json)')], default='', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='ModelUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.FloatField()),
                ('status', models.CharField(max_length=20)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='core.aimodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
