# Generated by Django 5.2.12 on 2026-04-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_aimodel_output_extension_modelusage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelusage',
            name='duration_seconds',
        ),
        migrations.AddField(
            model_name='modelusage',
            name='cpu_usage_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelusage',
            name='error_code',
            field=models.CharField(default='SUCCESS', max_length=50),
        ),
        migrations.AddField(
            model_name='modelusage',
            name='execution_time_seconds',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='modelusage',
            name='init_time_seconds',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='modelusage',
            name='input_size_bytes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modelusage',
            name='output_token_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelusage',
            name='output_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='modelusage',
            name='peak_memory_mb',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
