# Generated by Django 5.2.13 on 2026-04-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_is_subscribed_user_last_credit_refresh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
