# Generated by Django 5.2.13 on 2026-04-15 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_subscription_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='purchased_credits',
            field=models.IntegerField(default=0),
        ),
    ]
