# Generated by Django 5.2.13 on 2026-04-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_purchased_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
